[supervisord]
nodaemon = true
user = nuxt
logfile = /dev/stdout
logfile_maxbytes = 0
loglevel = info
pidfile = /tmp/supervisord.pid

[program:nuxt]
user = nuxt
autorestart = true
command = npm run start
directory = /app
redirect_stderr = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
 
[program:nginx]
user = nuxt
autorestart = true
command = nginx -g "daemon off;"
redirect_stderr = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
